spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: admin-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://oyxq:wwww@eureka-7001.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: beta
  application: 
    name: admin-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://oyxq:wwww@eureka-7001.com:7001/eureka/