spring:
  profiles:
   active: dev
---

server:
  port: 8001
  #context-path: /zf 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis配置文件路径
  type-aliases-package: com.zf.admin.api.vo                 #定义所有操作类的别名所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml    #所有mapper映射文件
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_8001
    username: root
    password: 123456
    dbcp2:
      min-idle: 5     #数据库连接池最小链接数
      initial-size: 5 #初始化链接大小
      max-total: 5    #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
  application:
    name: admin-config-client-dept
eureka:
  client:   #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://oyxqdev:wwww@eureka-7001.com:7001/eureka/    #配置eureka服务地址
    instance:
      lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 90 # 如果现在超过了5秒的间隔（默认是90秒）
      instance-id: dept-8001.com                          # 在信息列表时显示主机名称
      prefer-ip-address: true                             # 访问的路径变为IP地址
      
info:
  app.name: admin-config-client-dept
  company.name: www.sjy.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$	
---
server:
  port: 8001
  #context-path: /zf 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis配置文件路径
  type-aliases-package: com.zf.admin.api.vo                 #定义所有操作类的别名所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml    #所有mapper映射文件
spring:
  profiles: bate
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_8001
    username: root
    password: 123456
    dbcp2:
      min-idle: 5     #数据库连接池最小链接数
      initial-size: 5 #初始化链接大小
      max-total: 5    #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
  application:
    name: admin-config-client-dept
eureka:
  client:   #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://oyxqbate:wwww@eureka-7001.com:7001/eureka/    #配置eureka服务地址
    instance:
      lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 90 # 如果现在超过了5秒的间隔（默认是90秒）
      instance-id: dept-8001.com                          # 在信息列表时显示主机名称
      prefer-ip-address: true                             # 访问的路径变为IP地址
      
info:
  app.name: admin-config-client-dept
  company.name: www.sjy.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$	